name: docker
on:
  push:

jobs:
  push_to_registry:
    name: Push to ghcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v6,linux/ppc64le
          push: true
          tags: |
            ghcr.io/judge2020/docker-bonnie:latest
            ghcr.io/judge2020/docker-bonnie:2.00a
