name: docker
on:
  push:

jobs:
  push_to_registry:
    name: Push to ghcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to ghcr
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: judge2020/docker-bonnie
          tag_with_ref: true
